import { NextRequest, NextResponse } from 'next/server';
import { after } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { createAIDefence } from '@claude-flow/aidefence';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { cacheLookupMem, cacheLookupPiBrain, cacheStore, CachedResponse } from '@/lib/pi-brain';
import { rerank } from '@/lib/rerank';
import { validateCitations, verifyClaimsAgainstCitations, rewriteToHedge, appendVerifierStats } from '@/lib/validate-citations';
import { checkRateLimit, recordCall, isQaBypass } from '@/lib/rate-limit';
import { appendPerfStats } from '@/lib/perf-stats';

// Bumped from 60s → 120s. The pipeline (hybrid retrieval → MMR → cross-encoder
// rerank → synthesis → citation validation → claim verification → optional
// hedge rewrite) regularly touches 35-50s on cache miss; the prior 60s ceiling
// was producing 504s on cold starts. Verification stays inline because the
// hedged/cleaned report is the user-facing artifact, not a side-channel.
export const maxDuration = 120;
export const dynamic = 'force-dynamic';

// ─── AIMDS middleware (CLAUDE.md Rule 8) ─────────────────────────
// Scans inbound user queries for prompt injection, jailbreak attempts,
// and adversarial content. Outbound LLM responses are scanned async
// via after() as an audit trail — they don't gate the response.
const aidefence = createAIDefence({ enableLearning: true });

// Content + RVF are bundled in public/data/ — ships with Vercel deployment
const DATA_DIR = join(process.cwd(), 'public', 'data');

interface ContentEntry {
  c: string;    // text content
  v: string;    // video ID
  t: string;    // timestamp
  s: number;    // start ms
  p: string[];  // topics
  m: string[];  // speakers mentioned
  sk?: string;  // primary speaker key from per-turn chunker (or 'unknown')
  u: string;    // youtube URL
}

// ─── Lazy caches ────────────────────────────────────────────────
let contentIndexCache: Record<string, ContentEntry> | null = null;
let rvfCache: any = null;
let episodeDatesCache: Record<string, string> | null = null;
let embeddingsBinCache: Float32Array | null = null;
let embeddingsOrderCache: string[] | null = null;
const EMBEDDING_DIMS = 384;
const EMBEDDING_MODEL = 'text-embedding-3-small';

function getEmbeddingsBin(): { bin: Float32Array; order: string[] } | null {
  if (embeddingsBinCache && embeddingsOrderCache) {
    return { bin: embeddingsBinCache, order: embeddingsOrderCache };
  }
  try {
    const binPath = join(DATA_DIR, 'embeddings.bin');
    const orderPath = join(DATA_DIR, 'embeddings-order.json');
    if (!existsSync(binPath) || !existsSync(orderPath)) return null;
    const buf = readFileSync(binPath);
    // Copy into a fresh ArrayBuffer to guarantee 4-byte alignment for Float32Array.
    // Node's Buffer pool may hand out non-4-aligned byteOffsets for small/shared
    // buffers; slicing forces a dedicated, properly-aligned ArrayBuffer.
    const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
    embeddingsBinCache = new Float32Array(ab);
    embeddingsOrderCache = JSON.parse(readFileSync(orderPath, 'utf8'));
    return { bin: embeddingsBinCache, order: embeddingsOrderCache! };
  } catch (err) {
    console.error('Embeddings binary load failed:', err);
    return null;
  }
}

async function getContentIndex(): Promise<Record<string, ContentEntry>> {
  if (contentIndexCache) return contentIndexCache;
  const indexPath = join(DATA_DIR, 'content-index.json');
  if (!existsSync(indexPath)) {
    throw new Error('Content index not found');
  }
  contentIndexCache = JSON.parse(readFileSync(indexPath, 'utf8'));
  return contentIndexCache!;
}

function getEpisodeDates(): Record<string, string> {
  if (episodeDatesCache) return episodeDatesCache;
  const datesPath = join(DATA_DIR, 'episode-dates.json');
  if (!existsSync(datesPath)) {
    episodeDatesCache = {};
    return episodeDatesCache;
  }
  episodeDatesCache = JSON.parse(readFileSync(datesPath, 'utf8'));
  return episodeDatesCache!;
}

// ─── Episode metadata cache (Issue C fix) ───────────────────────────────────
// episodes_metadata.json is a list with title+date but no videoId.
// episode-dates.json has videoId→date. We join them by date to build
// a videoId→{title, episodeNumber} lookup.
interface EpisodeMeta { title: string; episodeNumber?: number }
let episodeMetaCache: Record<string, EpisodeMeta> | null = null;

function getEpisodeMetadata(): Record<string, EpisodeMeta> {
  if (episodeMetaCache) return episodeMetaCache;
  try {
    // Reads pre-built episode-meta.json from public/data (generated by build-knowledge-base.mjs).
    // Shape: { [videoId]: { title: string, episodeNumber?: number } }
    const builtPath = join(DATA_DIR, 'episode-meta.json');
    if (existsSync(builtPath)) {
      episodeMetaCache = JSON.parse(readFileSync(builtPath, 'utf8'));
      return episodeMetaCache!;
    }
    // File not found — return empty so citations degrade gracefully (episode=null)
    episodeMetaCache = {};
  } catch (err) {
    console.error('[getEpisodeMetadata] failed:', err);
    episodeMetaCache = {};
  }
  return episodeMetaCache!;
}

// ─── Data freshness snapshot ─────────────────────────────────────────────────
// Computes corpus stats once per cold start for the top-level `dataFreshness`
// block returned in every API response (Issue C / Move 11 freshness signal).
interface DataFreshness { newestEpisodeDate: string | null; totalEpisodes: number; totalChunks: number }
let dataFreshnessCache: DataFreshness | null = null;

async function getDataFreshness(): Promise<DataFreshness> {
  if (dataFreshnessCache) return dataFreshnessCache;
  try {
    // Check for pre-built freshness.json first (written by build-episode-dates.mjs)
    const freshnessPath = join(DATA_DIR, 'freshness.json');
    if (existsSync(freshnessPath)) {
      const f = JSON.parse(readFileSync(freshnessPath, 'utf8'));
      const index = await getContentIndex();
      dataFreshnessCache = {
        newestEpisodeDate: f.latestEpisode?.date || f.dateRange?.newest || null,
        totalEpisodes: f.episodeCount || 0,
        totalChunks: Object.keys(index).length,
      };
      return dataFreshnessCache;
    }
    // Fallback: compute from episode-dates + content-index
    const dates = getEpisodeDates();
    const index = await getContentIndex();
    const allDates = Object.values(dates).filter(Boolean).sort();
    dataFreshnessCache = {
      newestEpisodeDate: allDates.length > 0 ? allDates[allDates.length - 1] : null,
      totalEpisodes: Object.keys(dates).length,
      totalChunks: Object.keys(index).length,
    };
  } catch (err) {
    console.error('[getDataFreshness] failed:', err);
    dataFreshnessCache = { newestEpisodeDate: null, totalEpisodes: 0, totalChunks: 0 };
  }
  return dataFreshnessCache!;
}

let idfCache: Record<string, number> | null = null;
function getIdf(): Record<string, number> {
  if (idfCache) return idfCache;
  const idfPath = join(DATA_DIR, 'idf.json');
  if (!existsSync(idfPath)) {
    idfCache = {};
    return idfCache;
  }
  idfCache = JSON.parse(readFileSync(idfPath, 'utf8'));
  return idfCache!;
}

// BM25 doc-lengths cache — { [chunkId]: tokenCount, "__avgdl__": number }
// Built by build-idf.mjs alongside idf.json.
let docLengthsCache: Record<string, number> | null = null;
function getDocLengths(): Record<string, number> {
  if (docLengthsCache) return docLengthsCache;
  const dlPath = join(DATA_DIR, 'doc-lengths.json');
  if (!existsSync(dlPath)) {
    docLengthsCache = {};
    return docLengthsCache;
  }
  docLengthsCache = JSON.parse(readFileSync(dlPath, 'utf8'));
  return docLengthsCache!;
}

/**
 * Fair-use citation truncation. Caps verbatim transcript quotes at QUOTE_MAX_CHARS
 * to keep the per-citation excerpt short enough to qualify as fair-use commentary
 * rather than substantial reproduction. When the source chunk is longer, we prefer
 * the first sentence containing the query's highest-IDF (most distinctive) token —
 * that's usually the most relevant sentence to cite. Falls back to first 280 chars
 * with an ellipsis when no IDF-anchored sentence fits in the budget.
 */
const QUOTE_MAX_CHARS = 280;
function truncateQuoteForFairUse(chunk: string, query: string): string {
  if (!chunk) return '';
  if (chunk.length <= QUOTE_MAX_CHARS) return chunk;

  // Split into sentences on . ? ! followed by space/end. Keep the punctuation.
  const sentences = chunk.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g) ?? [chunk];

  // Pick the highest-IDF query token (rarer = more distinctive).
  const idf = getIdf();
  const queryTokens = query
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length >= 3);
  let topToken: string | null = null;
  let topIdf = -Infinity;
  for (const t of queryTokens) {
    const score = idf[t] ?? 5.5;
    if (score > topIdf) {
      topIdf = score;
      topToken = t;
    }
  }

  if (topToken) {
    const needle = topToken;
    for (const s of sentences) {
      if (s.toLowerCase().includes(needle) && s.trim().length <= QUOTE_MAX_CHARS) {
        return s.trim();
      }
    }
  }

  return chunk.slice(0, QUOTE_MAX_CHARS - 1).trimEnd() + '…';
}

/**
 * Compute a recency weight multiplier for a given episode date.
 * Recent episodes get full weight (1.0); old episodes decay to a floor.
 *
 * @param videoId   Episode video ID to look up date for.
 * @param halfLife  Decay half-life in days (default 180 for biographical/factual).
 *                  Pass 90 for topical/opinion queries (tighter recency).
 * @param floor     Minimum weight floor (default 0.4).
 *                  Pass 0.15 for topical/opinion queries.
 */
function recencyWeight(videoId: string, halfLife = 180, floor = 0.4): number {
  const dates = getEpisodeDates();
  const dateStr = dates[videoId];
  if (!dateStr) return 0.85; // unknown date → slight penalty vs known-recent
  const episodeMs = new Date(dateStr).getTime();
  const ageDays = (Date.now() - episodeMs) / (1000 * 60 * 60 * 24);
  if (ageDays < 0) return 1.0;
  // Exponential decay with configurable half-life, floored
  return Math.max(floor, floor + (1 - floor) * Math.exp(-ageDays / halfLife));
}



async function getRvf() {
  if (rvfCache) return rvfCache;
  try {
    const { RvfDatabase } = await import('@ruvector/rvf');
    const rvfPath = join(DATA_DIR, 'all-in-expert.rvf');
    if (!existsSync(rvfPath)) return null;
    rvfCache = await RvfDatabase.openReadonly(rvfPath);
    return rvfCache;
  } catch {
    return null;
  }
}

/**
 * Embed the query using OpenAI text-embedding-3-small @ 384 dims, L2-normalized.
 * Matches the embedding space of the precomputed doc vectors in embeddings.bin
 * (built by scripts/build-embeddings-openai.mjs using the same model and dim).
 * Using the same model on both sides is required for cosine similarity to be
 * meaningful — an earlier version embedded the query with a different local
 * model, which silently broke semantic retrieval.
 */
async function embedQuery(query: string): Promise<Float32Array> {
  const apiKey = process.env.OPEN_AI_KEY || process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error('OPEN_AI_KEY/OPENAI_API_KEY not configured — required for query embedding');
  }
  const res = await fetch('https://api.openai.com/v1/embeddings', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: EMBEDDING_MODEL,
      input: query,
      dimensions: EMBEDDING_DIMS,
      encoding_format: 'float',
    }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`OpenAI embeddings ${res.status}: ${body.slice(0, 200)}`);
  }
  const data = await res.json();
  const raw: number[] = data?.data?.[0]?.embedding;
  if (!Array.isArray(raw) || raw.length !== EMBEDDING_DIMS) {
    throw new Error(`Unexpected embedding shape: ${raw?.length}`);
  }
  // L2-normalize so cosine == dot product against the pre-normalized doc vectors
  let norm = 0;
  for (let i = 0; i < EMBEDDING_DIMS; i++) norm += raw[i] * raw[i];
  norm = Math.sqrt(norm);
  const vec = new Float32Array(EMBEDDING_DIMS);
  if (norm > 0) {
    for (let i = 0; i < EMBEDDING_DIMS; i++) vec[i] = raw[i] / norm;
  }
  return vec;
}

// Load bestie facts once per cold start — these are ground-truth overrides
let bestieFactsCache: Record<string, any> | null = null;
function getBestieFacts(): Record<string, any> {
  if (bestieFactsCache) return bestieFactsCache;
  const path = join(DATA_DIR, 'bestie-facts.json');
  if (!existsSync(path)) {
    bestieFactsCache = {};
    return bestieFactsCache;
  }
  bestieFactsCache = JSON.parse(readFileSync(path, 'utf8'));
  return bestieFactsCache!;
}

// Load speaker profiles once per cold start — contains 50 sample quotes per bestie
let speakerProfilesCache: Record<string, any> | null = null;
function getSpeakerProfiles(): Record<string, any> {
  if (speakerProfilesCache) return speakerProfilesCache;
  const path = join(DATA_DIR, 'speaker-profiles.json');
  if (!existsSync(path)) {
    speakerProfilesCache = {};
    return speakerProfilesCache;
  }
  speakerProfilesCache = JSON.parse(readFileSync(path, 'utf8'));
  return speakerProfilesCache!;
}

/**
 * Returns 3 representative sample quotes per core bestie, cleaned of raw
 * transcript noise (>> markers, filler text). Quotes are hand-indexed to
 * maximise voice distinctiveness: Chamath's "Look," openers + big numbers,
 * Sacks' methodical framework-building, Friedberg's science reframes,
 * Jason's hype + moderator energy.
 *
 * Hand-selected indices per bestie:
 * Chamath: "Look," opener (#23), TX data-center electricity numbers (#21), strategic assertion (#48)
 * Sacks: power/democratic-power framework (#3), censorship analysis (#27), AI deal breakdown (#25)
 * Friedberg: AI-jobs / tech-progress framing (#12), stimulus scorecard (#33), Science Corner (#37)
 * Jason: COVID/adult-responsibilities opener (#39), "greatest business ever" (#23), 8-billion minds (#40)
 */
function getSpeakerVoiceExamples(): string {
  const profiles = getSpeakerProfiles();

  const QUOTE_INDICES: Record<string, number[]> = {
    chamath: [23, 21, 48],
    sacks: [3, 27, 25],
    friedberg: [12, 33, 37],
    calacanis: [39, 23, 40],
  };

  const LABELS: Record<string, string> = {
    chamath: 'CHAMATH',
    sacks: 'SACKS',
    friedberg: 'FRIEDBERG',
    calacanis: 'JASON',
  };

  const sections: string[] = [];

  for (const [key, indices] of Object.entries(QUOTE_INDICES)) {
    const speaker = profiles[key];
    if (!speaker || !Array.isArray(speaker.sampleQuotes)) continue;
    const label = LABELS[key];
    const quotes: string[] = [];

    for (const idx of indices) {
      const q = speaker.sampleQuotes[idx];
      if (!q) continue;
      let text: string = (q.text || '').trim();
      // Strip raw interview markers (>> Name. >> or >> Name:)
      text = text.replace(/>>[\s\w]+\.?\s*/g, ' ').replace(/\s{2,}/g, ' ').trim();
      // Trim to ~280 chars at a word boundary so quotes stay snappy
      if (text.length > 280) {
        const cut = text.lastIndexOf(' ', 280);
        text = cut > 200 ? text.slice(0, cut) + '\u2026' : text.slice(0, 280) + '\u2026';
      }
      if (text.length > 40) quotes.push(`  \u2022 "${text}"`);
    }

    if (quotes.length > 0) {
      sections.push(`${label} actually says things like:\n${quotes.join('\n')}`);
    }
  }

  return sections.join('\n\n');
}

/**
 * Semantic search via precomputed embeddings binary + pure-JS cosine.
 * This is the primary search path — RVF native module doesn't boot in
 * Vercel serverless, so we ship vectors as Float32 blobs and do the
 * similarity math in plain JS. ~30ms for 15k vectors.
 */
async function semanticSearchBin(query: string, limit: number, speakerFilter?: string | null) {
  const index = await getContentIndex();
  const embeddings = getEmbeddingsBin();
  if (!embeddings) {
    console.log('[semanticSearchBin] embeddings binary not available');
    return null;
  }
  console.log(`[semanticSearchBin] loaded ${embeddings.order.length} vectors, embedding query...`);

  let queryVec: Float32Array;
  try {
    queryVec = await embedQuery(query);
    console.log(`[semanticSearchBin] query embedded, dims=${queryVec.length}`);
  } catch (err) {
    console.error('[semanticSearchBin] Query embedding failed:', err);
    return null;
  }

  const { bin, order } = embeddings;
  const N = order.length;
  // Vectors from the build script are already L2-normalized, so cosine == dot product
  const results: Array<{ id: string; entry: ContentEntry; distance: number; rawDistance: number }> = [];

  for (let i = 0; i < N; i++) {
    const offset = i * EMBEDDING_DIMS;
    let dot = 0;
    for (let j = 0; j < EMBEDDING_DIMS; j++) {
      dot += queryVec[j] * bin[offset + j];
    }
    const id = order[i];
    const entry = index[id];
    if (!entry) continue;
    // Pre-filter by speakerKey (per-turn primary speaker) when available;
    // fall back to the alias-mention array `m` for older chunks without `sk`.
    if (speakerFilter) {
      const matchesSk = entry.sk && entry.sk !== 'unknown' && entry.sk === speakerFilter;
      const matchesM  = entry.m.includes(speakerFilter);
      if (!matchesSk && !matchesM) continue;
    }
    // Convert similarity (higher = better) to distance (lower = better), apply recency
    const rawDistance = 1 - dot;
    const rec = recencyWeight(entry.v);
    results.push({ id, entry, rawDistance, distance: rawDistance / rec });
  }

  results.sort((a, b) => a.distance - b.distance);
  return results.slice(0, limit);
}

/**
 * RVF (HNSW) semantic search — try first; falls back to bin+cosine if it
 * throws (native module compat, file missing, etc). Returns null on failure.
 *
 * NOTE on ID translation: RVF v0.2 assigns internal integer labels during
 * ingest and returns those labels (not the original string IDs) on query.
 * Our build-knowledge-base.mjs ingests entries in the same order as
 * embeddings-order.json, so RVF label N maps to embeddings-order[N-1].
 * We translate before hydrating from content-index.
 */
async function semanticSearchRvf(
  query: string,
  limit: number,
  speakerFilter?: string | null
) {
  const t0 = Date.now();
  const db = await getRvf();
  if (!db) {
    console.log('[semanticSearchRvf] RVF not available');
    return null;
  }
  try {
    const index = await getContentIndex();
    const embeddings = getEmbeddingsBin();
    const order = embeddings?.order;
    if (!order || order.length === 0) {
      console.log('[semanticSearchRvf] embeddings-order not available for ID translation');
      return null;
    }
    const queryVec = await embedQuery(query);
    // Over-fetch so we have room to filter by speaker + recency-rerank
    const rvfResults = await db.query(queryVec, limit * 3, { efSearch: 250 });
    const hydrated: Array<{
      id: string; entry: ContentEntry; distance: number; rawDistance: number;
    }> = [];
    let resolved = 0;
    for (const r of rvfResults) {
      // Translate RVF integer label → string content-index key via embeddings-order
      const label = parseInt(String(r.id), 10);
      if (!Number.isFinite(label) || label < 1 || label > order.length) continue;
      const contentKey = order[label - 1];
      const entry = index[contentKey];
      if (!entry) continue;
      resolved++;
      if (speakerFilter) {
        const matchesSk = entry.sk && entry.sk !== 'unknown' && entry.sk === speakerFilter;
        const matchesM  = entry.m.includes(speakerFilter);
        if (!matchesSk && !matchesM) continue;
      }
      const rec = recencyWeight(entry.v);
      hydrated.push({
        id: contentKey,
        entry,
        rawDistance: r.distance,
        distance: r.distance / rec,
      });
    }
    hydrated.sort((a, b) => a.distance - b.distance);
    const top = hydrated.slice(0, limit);
    console.log(
      `[semanticSearchRvf] HNSW ${rvfResults.length} raw → ${resolved} resolved → ${top.length} after speaker filter in ${Date.now() - t0}ms`
    );
    return top.length > 0 ? top : null;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.log(`[semanticSearchRvf] FAILED after ${Date.now() - t0}ms: ${msg}`);
    return null;
  }
}

/**
 * Semantic search: prefer RVF (HNSW) only when its index was built in the same
 * embedding space as the query model (text-embedding-3-small @ 384d). Otherwise
 * fall back to the flat binary scan over embeddings.bin (which IS rebuilt by
 * scripts/build-embeddings-openai.mjs and therefore guaranteed to match).
 *
 * Set ENABLE_RVF=1 once the RVF file has been rebuilt with OpenAI vectors.
 * Until then, querying the MiniLM-built RVF with OpenAI query vectors would
 * produce noise — exactly the bug the OpenAI re-embedding was meant to fix.
 */
async function semanticSearch(query: string, limit = 30, speakerFilter?: string | null) {
  await getContentIndex();

  // Tier 1: RVF (HNSW) — opt-in until index is rebuilt in the OpenAI vector space.
  if (process.env.ENABLE_RVF === '1') {
    const rvfResults = await semanticSearchRvf(query, limit, speakerFilter);
    if (rvfResults && rvfResults.length > 0) {
      return { results: rvfResults, mode: 'rvf' as const };
    }
  }

  // Tier 2: flat binary scan — same vector space as the query (OpenAI 384d),
  // ~30ms for 15k vectors. This is the primary semantic path until RVF is rebuilt.
  const binResults = await semanticSearchBin(query, limit, speakerFilter);
  if (binResults && binResults.length > 0) {
    return { results: binResults, mode: 'semantic' as const };
  }

  // All dense paths exhausted — return empty so hybridSearch can merge with tfidf.
  // Reported as 'empty' (not 'semantic') so downstream can distinguish a successful
  // semantic search that happened to return zero from one where every dense path failed.
  return { results: [] as Array<{ id: string; entry: ContentEntry; distance: number; rawDistance: number }>, mode: 'empty' as const };
}

// ─── BM25-Okapi sparse search (function name kept for backward compat) ────────
/**
 * BM25-Okapi (k1=1.5, b=0.75) sparse retrieval over the full content index.
 * Replaces prior TF-IDF — BM25 saturates term frequency and normalises for chunk
 * length, giving materially better idiom matching for podcast catchphrases
 * ("Best episode ever", "Science Corner", etc.) than raw TF-IDF.
 *
 * score(D,q) = sum_qi[ IDF(qi) * f(qi,D)*(k1+1) / (f(qi,D) + k1*(1-b+b*|D|/avgdl)) ]
 *
 * Separated from semanticSearch so hybridSearch() can run both in parallel.
 * Returns results sorted by distance (lower = better), same shape as semantic results.
 */
async function tfidfSearch(
  query: string,
  limit: number,
  speakerFilter?: string | null
): Promise<Array<{ id: string; entry: ContentEntry; distance: number; rawDistance: number }>> {
  const index = await getContentIndex();

  // BM25 hyperparameters (Okapi standard)
  const K1 = 1.5;
  const B  = 0.75;

  // Load IDF + doc-lengths (lazy-cached)
  const idf = getIdf();
  const docLengths = getDocLengths();
  const avgdl = (docLengths['__avgdl__'] as number) || 141.53; // fallback from build run

  // Tokenize query — same rules as build-idf.mjs (>2 chars, <30 chars)
  const queryTokens = query
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 2 && w.length < 30);

  // Stopwords — no retrieval signal
  const stopWords = new Set([
    'what', 'would', 'will', 'about', 'think', 'they', 'this', 'that', 'from',
    'have', 'been', 'should', 'could', 'does', 'with', 'going', 'their', 'then',
    'than', 'them', 'when', 'where', 'there', 'these', 'those', 'here', 'into',
    'just', 'like', 'over', 'some', 'such', 'take', 'very', 'much', 'each',
    'make', 'most', 'said', 'says', 'back', 'been', 'were', 'was', 'are',
    'you', 'the', 'and', 'for', 'but', 'not', 'has', 'had', 'who', 'why',
    'how', 'all', 'any', 'can', 'did', 'get', 'got', 'her', 'him', 'his',
    'its', 'let', 'out', 'see', 'she', 'too', 'two', 'use', 'way',
    'bestie', 'besties', 'show',
  ]);

  type QueryTerm = { term: string; idfScore: number; primary: boolean };
  const queryTerms: QueryTerm[] = [];
  const seenTerms = new Set<string>();

  for (const tok of queryTokens) {
    if (seenTerms.has(tok)) continue;
    seenTerms.add(tok);
    if (stopWords.has(tok)) continue;
    const termIdf = idf[tok] ?? 5.5; // unknown terms treated as rare
    queryTerms.push({ term: tok, idfScore: termIdf, primary: termIdf > 2.5 });
  }

  if (queryTerms.length === 0) return [];

  const primaryTerms = queryTerms.filter((t) => t.primary);

  const scored: Array<{ id: string; entry: ContentEntry; distance: number; rawDistance: number }> = [];

  for (const [id, entry] of Object.entries(index)) {
    if (speakerFilter) {
      const matchesSk = entry.sk && entry.sk !== 'unknown' && entry.sk === speakerFilter;
      const matchesM  = entry.m.includes(speakerFilter);
      if (!matchesSk && !matchesM) continue;
    }

    const content = entry.c.toLowerCase();

    // Fast pre-filter: at least one primary term must appear literally in the chunk
    if (primaryTerms.length > 0) {
      const hasPrimary = primaryTerms.some((pt) => content.includes(pt.term));
      if (!hasPrimary) continue;
    }

    // BM25 document length — fall back to avgdl when not in doc-lengths.json
    const dl = (docLengths[id] as number) || avgdl;
    const lenNorm = 1 - B + B * (dl / avgdl);

    let bm25Score = 0;
    for (const qt of queryTerms) {
      // Count whole-word occurrences of qt.term in content
      let f = 0;
      let pos = content.indexOf(qt.term);
      while (pos !== -1) {
        const before = pos === 0 ? ' ' : content[pos - 1];
        const after  = content[pos + qt.term.length] || ' ';
        if (!/[a-z0-9]/.test(before) && !/[a-z0-9]/.test(after)) {
          f++;
        }
        pos = content.indexOf(qt.term, pos + qt.term.length);
      }
      if (f === 0) continue;

      // BM25 term contribution
      const numerator   = f * (K1 + 1);
      const denominator = f + K1 * lenNorm;
      bm25Score += qt.idfScore * (numerator / denominator);
    }

    if (bm25Score > 0) {
      // Normalise to [0,1]: soft ceiling = sum of per-term max contribution (idf*(k1+1))
      const softCeil = queryTerms.reduce((s, t) => s + t.idfScore * (K1 + 1), 0) || 1;
      const normalized = Math.min(1, bm25Score / softCeil);
      const rawDistance = 1 - normalized;
      const rec = recencyWeight(entry.v);
      scored.push({ id, entry, rawDistance, distance: rawDistance / rec });
    }
  }

  scored.sort((a, b) => a.distance - b.distance);
  return scored.slice(0, limit);
}

// ─── Reciprocal Rank Fusion (k=60) ───────────────────────────────────────────
/**
 * Merge ranked lists from multiple retrievers via RRF.
 * score(doc) = sum_over_rankers( 1 / (k + rank_in_that_ranker) )
 * Higher RRF score = better. k=60 is the standard hyperparameter from the
 * original Cormack et al. paper — it suppresses outlier rank-1 dominance
 * while giving enough signal for top-20 documents.
 */
function rrfFuse<T extends { id: string }>(
  rankedLists: T[][],
  k = 60
): Map<string, { item: T; rrfScore: number; bestRank: number; listSize: number }> {
  const scores = new Map<string, { item: T; rrfScore: number; bestRank: number; listSize: number }>();
  for (let li = 0; li < rankedLists.length; li++) {
    const list = rankedLists[li];
    for (let rank = 0; rank < list.length; rank++) {
      const item = list[rank];
      const contribution = 1 / (k + rank + 1); // +1 so rank-0 is 1/(k+1)
      const existing = scores.get(item.id);
      if (existing) {
        existing.rrfScore += contribution;
        // Track the best (lowest) rank this item achieved across all rankers,
        // and the size of the list it achieved that rank in (for threshold math).
        if (rank < existing.bestRank) {
          existing.bestRank = rank;
          existing.listSize = list.length;
        }
      } else {
        scores.set(item.id, { item, rrfScore: contribution, bestRank: rank, listSize: list.length });
      }
    }
  }
  return scores;
}

// ─── Claim-bearing score ─────────────────────────────────────────────────────
/**
 * Score a chunk by how likely it is to contain a specific, claim-bearing
 * statement. Returns a value in [0, 0.8].
 *
 * Heuristic weights:
 *   +0.20  chunk contains any digit (numbers signal specific claims)
 *   +0.20  chunk contains $ or % (financial/quantitative claim)
 *   +0.15  opinion verb-phrase ("I think", "we should", etc.)
 *   +0.15  chunk length > 250 chars (longer → more developed argument)
 *   +0.10  non-empty, non-'unknown' speaker key (grounded attribution)
 *
 * Used in two places:
 *  1. RRF fusion: rrfScore × (1 + claimBearingScore) so claim-dense
 *     chunks rank higher before MMR.
 *  2. Post-MMR secondary swap: chunk scoring < 0.2 is swapped for an
 *     unselected candidate from same speaker scoring ≥ 0.4.
 */
function claimBearingScore(text: string, sk?: string): number {
  let score = 0;
  if (/\d/.test(text)) score += 0.20;
  if (/[$%]/.test(text)) score += 0.20;
  if (/\b(i think|we should|the problem is|the issue is|we need to|i would)\b/i.test(text)) score += 0.15;
  if (text.length > 250) score += 0.15;
  if (sk && sk !== 'unknown' && sk !== '') score += 0.10;
  return Math.min(score, 0.80);
}

// ─── Hybrid search (dense + sparse + RRF) ────────────────────────────────────
/**
 * Run semanticSearch and tfidfSearch in parallel, fuse with RRF (k=60),
 * apply recency weighting on top of RRF score, return top-limit results.
 *
 * Why k=60: standard from the RRF paper. Larger k smooths rank contributions
 * (good when retrievers disagree on rank-1); smaller k amplifies top-rank
 * winners. 60 balances precision and recall for our ~15k corpus.
 */
async function hybridSearch(
  query: string,
  limit = 30,
  speakerFilter?: string | null,
  topicalMode = false
): Promise<{ results: Array<{ id: string; entry: ContentEntry; distance: number; rawDistance: number }>; mode: 'hybrid' }> {
  // Over-fetch from each ranker so RRF has good coverage before trimming
  const fetchLimit = Math.min(limit * 3, 90);

  const [semanticResult, tfidfResults] = await Promise.all([
    semanticSearch(query, fetchLimit, speakerFilter),
    tfidfSearch(query, fetchLimit, speakerFilter),
  ]);

  const denseList = semanticResult.results;
  const sparseList = tfidfResults;

  console.log(
    `[hybridSearch] dense=${denseList.length} sparse=${sparseList.length} topical=${topicalMode}`
  );

  // If both rankers returned nothing, return empty
  if (denseList.length === 0 && sparseList.length === 0) {
    return { results: [], mode: 'hybrid' };
  }

  // RRF fusion
  const fused = rrfFuse([denseList, sparseList], 60);

  // Recency parameters depend on query type
  const halfLife = topicalMode ? 90 : 180;
  const floor = topicalMode ? 0.15 : 0.4;

  // Convert RRF scores to distance-like values for downstream compatibility.
  // Higher rrfScore → lower distance. Apply recency boost + claim-bias.
  //
  // Topical-relevance gate (iter-4 fix for q20/q07 regressions):
  // Claim-bias should only boost chunks already topically-relevant.
  // A chunk that appears only in the bottom-half of BOTH rankers is
  // likely off-topic — we cap its claim multiplier at 1.05 (near-zero boost)
  // so numeric density alone cannot rescue it. A chunk in the top-quartile
  // of EITHER ranker gets the full multiplier (up to 1.80). The threshold
  // interpolates linearly between these two cases.
  //
  // Gate logic:
  //   topHalf  = bestRank < listSize/2   → full multiplier allowed
  //   bottom-half on both rankers        → cap at 1.05
  //   top-quartile on either ranker      → full multiplier
  //
  // This prevents off-topic claim-dense chunks (e.g. Elon/Baker on tariffs)
  // from outranking on-topic less-claim-dense Sacks/Chamath chunks.
  const merged = Array.from(fused.values()).map(({ item, rrfScore, bestRank, listSize }) => {
    const rec = recencyWeight(item.entry.v, halfLife, floor);
    const rawClaimScore = claimBearingScore(item.entry.c, item.entry.sk);

    // topical gate: is this chunk in the top-half of its best ranker?
    const halfSize = listSize > 0 ? listSize / 2 : fetchLimit / 2;
    const quarterSize = listSize > 0 ? listSize / 4 : fetchLimit / 4;
    let claimCap: number;
    if (bestRank < quarterSize) {
      // Top-quartile of some ranker → topically strong, allow full claim boost
      claimCap = 1.80;
    } else if (bestRank < halfSize) {
      // Top-half but not top-quartile → moderate boost allowed
      claimCap = 1.40;
    } else {
      // Bottom-half of BOTH rankers → topically weak, minimal claim boost
      claimCap = 1.05;
    }
    const claimBias = Math.min(1 + rawClaimScore, claimCap);
    const biasedRrf = rrfScore * claimBias;
    // RRF score max ≈ 1/(k+1) + 1/(k+1) ≈ 0.032 for k=60; normalise to [0,1].
    // Distance = (1 - biasedRrf*31) gives ~0 for perfect, ~1 for irrelevant.
    const normalised = Math.min(1, biasedRrf * 31);
    const rawDistance = 1 - normalised;
    // Attach bestRank so the secondary-swap gate can check topical relevance
    return { ...item, rawDistance, distance: rawDistance / rec, rrfBestRank: bestRank, rrfListSize: listSize };
  });

  merged.sort((a, b) => a.distance - b.distance);
  return { results: merged.slice(0, limit), mode: 'hybrid' };
}

// ─── MMR diversity reranking ──────────────────────────────────────────────────
/**
 * Maximal Marginal Relevance reranking for diversity.
 * Iteratively selects the chunk that maximises:
 *   λ·sim(chunk, query) − (1−λ)·max_already_selected sim(chunk, selected_i)
 * with λ=0.7. Uses text-overlap Jaccard as a cheap similarity proxy (avoids
 * a second embedding pass). Same-episode penalty: second chunk from an
 * episode in the selected set gets a 0.5 diversity multiplier applied.
 *
 * Why λ=0.7: we weight relevance 70% vs diversity 30%. In a voice-synthesis
 * context you need the most relevant facts first; diversity is secondary.
 * λ<0.5 would produce maximally diverse but possibly tangential results.
 */
function mmrRerank(
  candidates: Array<{ id: string; entry: ContentEntry; distance: number; rawDistance: number }>,
  topK: number,
  lambda = 0.7
): Array<{ id: string; entry: ContentEntry; distance: number; rawDistance: number }> {
  if (candidates.length <= topK) return candidates;

  // Pre-compute token sets for Jaccard similarity (cheap text-overlap proxy)
  const tokenSets = candidates.map((c) => {
    const words = c.entry.c.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter((w) => w.length >= 3);
    return new Set(words);
  });

  // relevance(i) = 1 - distance (higher = better)
  const relevance = candidates.map((c) => Math.max(0, 1 - c.distance));

  function jaccard(a: Set<string>, b: Set<string>): number {
    if (a.size === 0 || b.size === 0) return 0;
    let inter = 0;
    for (const tok of a) if (b.has(tok)) inter++;
    return inter / (a.size + b.size - inter);
  }

  const selected: number[] = [];
  const selectedEpisodes = new Map<string, number>(); // episodeId → count
  const remaining = new Set(candidates.map((_, i) => i));

  while (selected.length < topK && remaining.size > 0) {
    let bestIdx = -1;
    let bestScore = -Infinity;

    for (const i of remaining) {
      // Max similarity to already-selected items
      let maxSim = 0;
      for (const j of selected) {
        const sim = jaccard(tokenSets[i], tokenSets[j]);
        if (sim > maxSim) maxSim = sim;
      }

      let score = lambda * relevance[i] - (1 - lambda) * maxSim;

      // Same-episode penalty: subtract a fixed amount per prior chunk from the
      // same episode. Subtraction (rather than multiplication) is required so
      // negative scores get more negative — multiplying by 0.5 would make a
      // negative score larger and accidentally REWARD same-episode duplicates.
      const SAME_EPISODE_PENALTY = 0.15;
      const sameEpCount = selectedEpisodes.get(candidates[i].entry.v) ?? 0;
      if (sameEpCount > 0) {
        score -= SAME_EPISODE_PENALTY * sameEpCount;
      }

      if (score > bestScore) {
        bestScore = score;
        bestIdx = i;
      }
    }

    if (bestIdx === -1) break;
    selected.push(bestIdx);
    remaining.delete(bestIdx);
    const ep = candidates[bestIdx].entry.v;
    selectedEpisodes.set(ep, (selectedEpisodes.get(ep) ?? 0) + 1);
  }

  return selected.map((i) => candidates[i]);
}

// ─── Bestie profiles ─────────────────────────────────────────────

const SPEAKER_CONTEXT: Record<string, { name: string; short: string; lens: string; style: string; tier: 'core' | 'guest' }> = {
  chamath: {
    name: 'Chamath Palihapitiya', short: 'Chamath', tier: 'core',
    lens: 'Venture capitalist (Social Capital). Capital allocation, market efficiency, systemic risk. Contrarian macro views.',
    style: 'Bold, contrarian, numbers-heavy. Takes unpopular positions backed by data.',
  },
  sacks: {
    name: 'David Sacks', short: 'Sacks', tier: 'core',
    lens: 'Enterprise SaaS investor (Craft Ventures), former PayPal COO. Jan 2025+: White House AI & Crypto Czar.',
    style: 'Analytical, measured, builds logical arguments. Frames issues as systems problems.',
  },
  friedberg: {
    name: 'David Friedberg', short: 'Friedberg', tier: 'core',
    lens: 'The Production Board CEO. Science first-principles. Called "Sultan of Science." Often "Freeberg" in transcripts.',
    style: 'Methodical, science-first. Reframes political debates as scientific/economic questions.',
  },
  calacanis: {
    name: 'Jason Calacanis', short: 'Jason', tier: 'core',
    lens: 'Angel investor, LAUNCH CEO, podcast host/moderator. Startup ecosystem insider.',
    style: "Provocative, asks uncomfortable questions, plays devil's advocate.",
  },
  gerstner: { name: 'Brad Gerstner', short: 'Gerstner', tier: 'guest', lens: 'Altimeter Capital. Long-term tech growth. Category-defining franchises.', style: 'Measured, analytical, references specific companies and metrics.' },
  gurley: { name: 'Bill Gurley', short: 'Gurley', tier: 'guest', lens: 'Benchmark GP. Late-stage VC and market structure. Skeptical of regulatory capture.', style: 'Pointed, historical, references market failures and missteps.' },
  baker: { name: 'Gavin Baker', short: 'Baker', tier: 'guest', lens: 'Atreides Management CIO. AI compute economics and semiconductor cycles.', style: 'Highly technical, brings granular data on compute and capex.' },
  thiel: { name: 'Peter Thiel', short: 'Thiel', tier: 'guest', lens: 'Founders Fund, Palantir co-founder. Contrarian philosophy, monopoly theory.', style: 'Philosophical, challenges frames rather than facts.' },
  ackman: { name: 'Bill Ackman', short: 'Ackman', tier: 'guest', lens: 'Pershing Square. Activist public-markets investor. Sharp macro views.', style: 'Direct, combative, names individuals and institutions.' },
  gracias: { name: 'Antonio Gracias', short: 'Gracias', tier: 'guest', lens: 'Valor Equity. Operational VC, deep Elon/Tesla network. Led DOGE investigations.', style: 'Quietly confident, brings operational receipts.' },
  elon: { name: 'Elon Musk', short: 'Elon', tier: 'guest', lens: 'Tesla/SpaceX/xAI. First-principles engineer-entrepreneur.', style: 'Direct, engineering-focused, brings concrete physics to abstract debates.' },
  naval: { name: 'Naval Ravikant', short: 'Naval', tier: 'guest', lens: 'AngelList co-founder. Philosopher-investor on wealth and leverage.', style: 'Concise aphorisms, deep frameworks.' },
  tucker: { name: 'Tucker Carlson', short: 'Tucker', tier: 'guest', lens: 'Populist conservative media. Skeptical of institutions and interventionism.', style: 'Rhetorical, interview format.' },
  rabois: { name: 'Keith Rabois', short: 'Rabois', tier: 'guest', lens: 'Khosla Ventures. Contrarian startup investor.', style: 'Provocative, takes extreme positions.' },
  lonsdale: { name: 'Joe Lonsdale', short: 'Lonsdale', tier: 'guest', lens: 'Palantir co-founder, 8VC. Defense tech and policy reform.', style: 'Action-oriented, concrete solutions.' },
  cuban: { name: 'Mark Cuban', short: 'Cuban', tier: 'guest', lens: 'Serial entrepreneur. Direct-to-consumer, healthcare cost reform.', style: 'Direct, data-driven on specific industries.' },
  kalanick: { name: 'Travis Kalanick', short: 'Kalanick', tier: 'guest', lens: 'Uber founder, CloudKitchens CEO. Physical-world disruption.', style: 'Aggressive, operator-focused.' },
  shapiro: { name: 'Ben Shapiro', short: 'Shapiro', tier: 'guest', lens: 'Daily Wire. Conservative commentary.', style: 'Rapid, fact-heavy, confrontational.' },
  saagar: { name: 'Saagar Enjeti', short: 'Saagar', tier: 'guest', lens: 'Breaking Points. Populist political journalism.', style: 'Journalistic, historical context.' },
};

function sec(ms: number) {
  return Math.max(0, Math.floor(ms / 1000));
}

export async function POST(req: NextRequest) {
  const reqStart = Date.now();
  try {
    const body = await req.json();
    const { query, speaker, mode, strictSpeaker } = body;
    // QA bypass token: accepted from POST body, ?qa_token=<t> query param,
    // or `x-qa-token` header. When it matches process.env.QA_BYPASS_TOKEN
    // the rate-limit check short-circuits and the counter is NOT incremented.
    const qaToken: string | null =
      (typeof body?.qa_token === 'string' && body.qa_token) ||
      req.nextUrl?.searchParams?.get('qa_token') ||
      req.headers.get('x-qa-token') ||
      null;
    const qaBypassActive = isQaBypass(qaToken);
    // strictSpeaker: when true AND a speaker filter is set, skip the
    // filtered+unfiltered hybrid-search interleave entirely. Only return
    // chunks matching the speaker filter. Echoed back to the UI as
    // `strictMode` so the frontend can render a "STRICT MODE ACTIVE" badge.
    const strictModeActive = Boolean(strictSpeaker) && Boolean(speaker);

    if (!query || typeof query !== 'string') {
      return NextResponse.json({ error: 'Query is required' }, { status: 400 });
    }

    // ─── AIMDS inbound scan ────────────────────────────────────────
    // Block prompt injection, jailbreak attempts, and adversarial inputs
    // before they reach retrieval or synthesis. ~1-3ms overhead.
    const inboundCheck = await aidefence.detect(query);
    if (!inboundCheck.safe) {
      const topThreat = inboundCheck.threats[0];
      const reason = topThreat?.description ?? 'Adversarial content detected';
      console.warn('[AIMDS] Inbound query blocked:', { reason, threats: inboundCheck.threats.map((t: { type: string; severity: string; confidence: number }) => ({ type: t.type, severity: t.severity, confidence: t.confidence })) });
      return NextResponse.json(
        { error: 'Query blocked by safety filter', reason },
        { status: 400 }
      );
    }

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ error: 'ANTHROPIC_API_KEY not configured' }, { status: 500 });
    }

    // ─── Tier 1: in-memory cache (sync, ~1ms) ──────────────────────
    // Cache hits are free — they don't invoke Claude and don't count
    // against the daily rate limit.
    // Include strictModeActive in the cache key so strict-only retrievals
    // (smaller, speaker-only segment pool) don't share a cache entry with
    // the default interleaved retrieval — the citations are materially different.
    const cacheKey = {
      query: strictModeActive ? `${query} __strict__` : query,
      speaker: speaker || null,
      mode: mode || null,
    };
    const memHit = cacheLookupMem(cacheKey);
    if (memHit) {
      // Re-compute corpus freshness on every cache hit so the frontend's
      // "Corpus current as of [date]" indicator stays populated. The helper
      // memoizes per cold-start, so this is effectively free.
      const dataFreshness = await getDataFreshness();
      return NextResponse.json({
        ...memHit,
        cacheHit: true,
        cacheSource: 'mem',
        latencyMs: Date.now() - reqStart,
        strictMode: strictModeActive,
        dataFreshness,
      });
    }

    // ─── Rate limit check (soft global 200/day, resets UTC midnight) ─
    // Only new syntheses count; cached responses are free. If the daily
    // budget is exhausted, return 429 with a user-friendly message.
    // QA harness requests carrying a valid qaToken bypass this entirely
    // (rl.bypassed === true) and never consume budget via recordCall().
    const rl = await checkRateLimit(qaToken);
    if (!rl.allowed) {
      return NextResponse.json(
        {
          error: 'Daily query limit reached',
          message: `This research tool is running on a budget-capped demo (${rl.limit} new synthesis calls per day). Come back after ${new Date(rl.resetsAt).toUTCString()}, or try a question that's been asked before (cache hits are free).`,
          dayKey: rl.dayKey,
          count: rl.count,
          limit: rl.limit,
          resetsAt: rl.resetsAt,
          suspended: true,
        },
        { status: 429 }
      );
    }

    // ─── Speculative parallel: pi-brain lookup || retrieval ────────
    // Run both concurrently. Pi-brain hit wins if it completes before
    // retrieval; otherwise we stick with retrieval and proceed to synthesis.
    //
    // Retrieval now uses hybridSearch (dense + sparse + RRF k=60) so both
    // topical catchphrases (TF-IDF) and semantic similarity contribute.
    // When a speaker filter is active we run filtered AND unfiltered hybrid
    // searches in parallel so the LLM gets both voice-matched segments and
    // topic-grounded segments to paraphrase in the speaker's voice.
    //
    // isTopical: opinion/speaker queries use tighter recency (90d half-life,
    // 0.15 floor); biographical/factual mode keeps the wider 180d/0.4 defaults.
    const isTopical = !mode || mode === 'topical' || !!speaker;
    const piBrainPromise = cacheLookupPiBrain(cacheKey).catch(() => null);
    const retrievalPromise = (async () => {
      if (speaker) {
        // ─── Strict speaker mode ─────────────────────────────────────
        // User explicitly asked for ONLY this bestie's chunks. Skip the
        // unfiltered interleave entirely. If fewer than SEGMENT_BUDGET
        // matches come back, we return what we have rather than padding
        // with unfiltered topic-only chunks (that would defeat the point).
        if (strictModeActive) {
          const filtered = await hybridSearch(query, 40, speaker, true);
          return { results: filtered.results, mode: 'hybrid-strict' as const };
        }
        const [filtered, unfiltered] = await Promise.all([
          hybridSearch(query, 20, speaker, true),
          hybridSearch(query, 20, null, true),
        ]);
        // Interleave: alternate filtered and unfiltered, dedupe by id,
        // preserve relative order. This gives the LLM both voice-matched
        // quotes AND topic-grounded segments to paraphrase in their voice.
        const seen = new Set<string>();
        const merged: typeof filtered.results = [];
        const maxLen = Math.max(filtered.results.length, unfiltered.results.length);
        for (let i = 0; i < maxLen && merged.length < 40; i++) {
          for (const r of [filtered.results[i], unfiltered.results[i]]) {
            if (!r) continue;
            if (seen.has(r.id)) continue;
            seen.add(r.id);
            merged.push(r);
          }
        }
        return { results: merged, mode: 'hybrid' as const };
      }
      return hybridSearch(query, 40, null, isTopical);
    })();

    // Wait for either pi-brain to resolve (hit or miss) OR retrieval to finish.
    // Whichever completes first wins. On pi-brain miss (null resolve), we still
    // wait for retrieval. On retrieval finish before pi-brain, we discard
    // pi-brain and proceed.
    const raceResult = await Promise.race([
      piBrainPromise.then((v) => ({ kind: 'pi', value: v })),
      retrievalPromise.then((v) => ({ kind: 'retrieval', value: v })),
    ]);

    if (raceResult.kind === 'pi' && raceResult.value) {
      // Re-compute corpus freshness on cross-instance cache hits too —
      // pi-brain CachedResponse objects don't persist this field.
      const dataFreshness = await getDataFreshness();
      return NextResponse.json({
        ...raceResult.value,
        cacheHit: true,
        cacheSource: 'pi-brain',
        latencyMs: Date.now() - reqStart,
        strictMode: strictModeActive,
        dataFreshness,
      });
    }

    // Either retrieval won the race, or pi-brain returned null. Ensure
    // retrieval's result is awaited (it may or may not be done yet).
    const { results: rawResults, mode: searchMode } = await retrievalPromise;
    // Timing marker: retrieval (hybrid dense+sparse + RRF) is now complete.
    const tRetrieve = Date.now() - reqStart;

    if (rawResults.length === 0) {
      return NextResponse.json({
        report: strictModeActive
          ? `No segments matching only ${speaker}'s voice were found for this query. Try turning strict mode off, or rephrase the question.`
          : 'No relevant segments found in the archive for this query. Try rephrasing or asking about a different topic.',
        segmentsFound: 0,
        totalEntries: Object.keys(await getContentIndex()).length,
        searchMode,
        strictMode: strictModeActive,
      });
    }

    // ─── MMR diversity reranking ──────────────────────────────────
    // After hybrid retrieval, select top-N via Maximal Marginal Relevance:
    // maximises relevance while penalising near-duplicate chunks and chunks
    // from episodes already represented. Same-episode second chunk gets a
    // 0.5 score multiplier. This prevents 5 chunks from the same episode.
    //
    // Issue B fix: use λ=0.5 (balance relevance/diversity) for topical/opinion
    // queries (speaker filter present OR isTopical flag). λ=0.7 (relevance-heavy)
    // for factual/biographical queries where topic-drift is less harmful.
    // λ=0.5 prevents the top-12 drifting off-topic when diversity is overweighted.
    const SEGMENT_BUDGET = 12;
    const mmrLambda = (isTopical || !!speaker) ? 0.5 : 0.7;
    // Expand candidate pool to SEGMENT_BUDGET * 4 (48) so claim-swap has
    // enough unselected candidates to work with after MMR selects top-12.
    const mmrResults = mmrRerank(rawResults, Math.min(rawResults.length, SEGMENT_BUDGET * 4), mmrLambda);

    // ─── Secondary claim-bearing filter ──────────────────────────────
    // After MMR, scan the top-SEGMENT_BUDGET. If a chunk's claimBearingScore
    // is < 0.2 (topically near but claim-poor) AND there is an unselected
    // candidate from the same speaker with score ≥ 0.4, swap them in.
    // This prevents the "all topically-near, none claim-bearing" failure mode.
    const selectedIds = new Set(mmrResults.slice(0, SEGMENT_BUDGET).map((r) => r.id));
    const unselected = mmrResults.slice(SEGMENT_BUDGET); // candidates beyond top-12
    const claimFiltered = mmrResults.slice(0, SEGMENT_BUDGET).map((r) => {
      const cs = claimBearingScore(r.entry.c, r.entry.sk || undefined);
      if (cs >= 0.2) return r; // already claim-bearing, keep
      // Find an unselected candidate from the same speaker with higher claim score.
      // iter-4 fix: only swap in a candidate that was topically relevant
      // (top-30 of its best ranker). Prevents claim-dense but off-topic
      // chunks from being pulled in via secondary swap.
      const TOP_SWAP_RANK = 30;
      const swapIdx = unselected.findIndex(
        (u) =>
          !selectedIds.has(u.id) &&
          (u.entry.sk || 'unknown') === (r.entry.sk || 'unknown') &&
          claimBearingScore(u.entry.c, u.entry.sk || undefined) >= 0.4 &&
          ((u as any).rrfBestRank ?? Infinity) < TOP_SWAP_RANK
      );
      if (swapIdx === -1) return r; // no suitable swap found
      const swap = unselected.splice(swapIdx, 1)[0];
      selectedIds.add(swap.id);
      selectedIds.delete(r.id);
      console.log(`[claimSwap] swapped claim-poor chunk ${r.id} → ${swap.id} (speaker=${r.entry.sk}, rrfBestRank=${(swap as any).rrfBestRank ?? 'n/a'})`);
      return swap;
    });

    // ─── Cross-encoder rerank (Haiku as relevance scorer) ──────────
    // Cosine similarity is approximate; an LLM read of "does this segment
    // answer this query?" produces materially better top-K. Adds ~500ms,
    // saves multiple seconds downstream by giving synthesis better material.
    const results = await rerank(query, claimFiltered, SEGMENT_BUDGET, apiKey);
    // Timing marker: MMR + claim-swap + cross-encoder rerank complete.
    const tRerank = Date.now() - reqStart;

    // Build citation-enriched segment text for the LLM
    // Include episode date so Claude can apply the recency rule
    const epDates = getEpisodeDates();
    const segmentText = results
      .slice(0, SEGMENT_BUDGET)
      .map((r, i) => {
        const topics = r.entry.p.join(', ');
        const speakers = r.entry.m.length > 0 ? ` · voices: ${r.entry.m.join(', ')}` : '';
        const epDate = epDates[r.entry.v] || 'date-unknown';
        return `[${i + 1}] episode-date: ${epDate} · timestamp: ${r.entry.t} · topics: ${topics}${speakers}\nSEGMENT: "${r.entry.c.slice(0, 600)}"`;
      })
      .join('\n\n');

    // ─── Thin-evidence gate ───────────────────────────────────────────────────
    // Extract key entities from the query (capitalized words, quoted strings,
    // and known proper nouns) to count how many retrieved segments mention them.
    // If fewer than 3 citations contain any key entity, flag thinEvidence=true
    // so we can reinforce the hedge-or-refuse protocol in the system prompt.
    function extractKeyEntities(q: string): string[] {
      const entities: string[] = [];
      // Quoted strings (highest signal)
      const quoted = q.match(/"([^"]+)"/g);
      if (quoted) entities.push(...quoted.map((s) => s.replace(/"/g, '').toLowerCase()));
      // Capitalized words (likely proper nouns): 2+ chars, starts uppercase, not at start of sentence
      const caps = q.match(/(?<![.!?]\s)(?<!\bI\b\s)\b[A-Z][a-z]{2,}\b/g);
      if (caps) entities.push(...caps.map((s) => s.toLowerCase()));
      // Deduplicate and filter out common non-entity caps
      const stopCaps = new Set(['what', 'how', 'why', 'when', 'where', 'who', 'will', 'does', 'would']);
      return [...new Set(entities)].filter((e) => e.length >= 3 && !stopCaps.has(e));
    }

    const keyEntities = extractKeyEntities(query);
    let directHits = 0;
    if (keyEntities.length > 0) {
      for (const r of results.slice(0, SEGMENT_BUDGET)) {
        const text = r.entry.c.toLowerCase();
        if (keyEntities.some((e) => text.includes(e))) directHits++;
      }
    } else {
      // No extractable entities — trust the retriever, treat as sufficient
      directHits = SEGMENT_BUDGET;
    }
    const thinEvidence = directHits < 3;
    if (thinEvidence) {
      console.log(
        `[thin-evidence] query="${query}" entities=${JSON.stringify(keyEntities)} directHits=${directHits}/${results.length} — hedge protocol active`
      );
    }

    // Structured citations for the response (frontend renders these separately)
    // Issue C fix: join episode metadata (title, episodeNumber) from episodes_metadata.json
    // keyed via videoId. getEpisodeMetadata() builds the join lazily on first call.
    const epMeta = getEpisodeMetadata();
    const citations = results.slice(0, SEGMENT_BUDGET).map((r, i) => {
      const meta = epMeta[r.entry.v];
      return {
        n: i + 1,
        time: r.entry.t,
        date: epDates[r.entry.v] || null,
        episode: meta?.title || null,
        episodeNumber: meta?.episodeNumber ?? null,
        videoId: r.entry.v,
        url: r.entry.u,
        topics: r.entry.p,
        speakers: r.entry.m,
        speakerKey: r.entry.sk || null, // primary speaker from per-turn chunker
        quote: truncateQuoteForFairUse(r.entry.c, query),
        // Use rawDistance (pre-recency) for the user-facing score so old episodes
        // with low recency weight don't render as negative relevance percentages.
        // The recency-adjusted `distance` is kept internal for ranking only.
        relevance: Number(Math.max(0, Math.min(1, 1 - r.rawDistance)).toFixed(3)),
      };
    });

    // Load ground-truth facts about each bestie — OVERRIDES anything fuzzy from retrieval
    const bestieFacts = getBestieFacts();
    const factsText = Object.entries(bestieFacts)
      .map(([, f]: [string, any]) => {
        const positions = (f.current_positions || []).map((p: string) => `  - ${p}`).join('\n');
        return `• **${f.name}** — ${f.role}\n  Political: ${f.political_alignment}\n  Current positions:\n${positions}\n  Voice: ${f.style}`;
      })
      .join('\n\n');

    const speakerProfileText = Object.entries(SPEAKER_CONTEXT)
      .map(([, s]) => `• ${s.name} (${s.short}, ${s.tier}) — ${s.lens} | Style: ${s.style}`)
      .join('\n');

    // Load actual sample quotes from speaker-profiles.json to ground voice synthesis
    const voiceExamples = getSpeakerVoiceExamples();

    const focus = speaker ? SPEAKER_CONTEXT[speaker] : null;
    const isForecast = mode === 'forecast';

    const systemPrompt = `You are writing in the voices of the All-In Podcast hosts. You have read hundreds of hours of their actual transcripts and know exactly how each one speaks, argues, and thinks.

YOU ARE NOT WRITING ANALYSIS. You are writing a synthesized round-table discussion — as if the four besties were together right now, debating the user's question. The output should read like a fresh All-In segment, not like an academic report about them.

═══ GROUND-TRUTH FACTS — ABSOLUTE OVERRIDE ═══

These are VERIFIED FACTS. They are more authoritative than anything in the retrieved transcript segments. Older transcripts may reflect positions the besties held YEARS AGO that have since changed — especially political alignment, which has realigned significantly since 2022. You MUST write the current state as described here, not a hedged "used to be X, now Y" hedge.

${factsText}

**ABSOLUTE RULES ABOUT THE FACTS:**
1. David Sacks is a REPUBLICAN. He works for Donald Trump as White House AI & Crypto Czar. He keynoted the 2024 Republican National Convention. He hosted a major Trump fundraiser. Do not call him "centrist", "moderate", "independent", "in the middle", or "a former Democrat who's now independent". He is a partisan Republican. If someone asks "is Sacks a Democrat or Republican?", the answer is REPUBLICAN — full stop — no qualification, no hedging, no "it's complicated".
2. Chamath Palihapitiya publicly endorsed Trump in 2024 and votes Republican.
3. Friedberg is libertarian-leaning but voted Trump in 2024.
4. Jason Calacanis is the most moderate, but even he has moved right on economic/cultural issues.
5. If the retrieved segments contain OLD quotes (pre-2024) where a bestie described themselves differently, those are HISTORICAL — the current state is what the FACTS say above. Write the dialogue in the present, reflecting current reality.
6. On any question about CURRENT political alignment, role, or bio fact — answer from FACTS, NOT from retrieval. The retrieval is for topical views, not biographical questions.

═══ THE VOICES ═══

**JASON (Jason Calacanis)** — The host. He sets up topics, interrupts, hypes, and steers. Warm, theatrical, occasionally needs to be reined in. He asks the uncomfortable question and then says "this is wild" or "banger" when the answer surprises him. Signature beats: intro hype, "let's move on to the next topic", "best episode ever", earnest questions about founders. He's the one pulling the thread, not the one making the deepest point.

**CHAMATH (Chamath Palihapitiya)** — The contrarian with numbers. Blunt, confident, willing to be unpopular. Opens with "Look," or "Honestly," or "The reality is" and then drops a specific statistic or historical analogy. Big on capital allocation, power laws, 80-year cycles, Ray Dalio frameworks. Dismissive of consensus, allergic to vibes-based arguments. Will say "That's wrong" directly. Reaches for the macro frame even on micro questions.

**SACKS (David Sacks)** — The systems lawyer. Measured, methodical, builds an argument brick by brick. Frames things as "the question is really X" or "let me give you the framework here." Enterprise SaaS pattern-matcher. As of January 2025 he's White House AI & Crypto Czar, so post-2025 he speaks from inside the administration on anything policy-adjacent. Historical parallels are his thing. Rarely raises his voice; rarely backs down.

**FRIEDBERG (David Friedberg)** — The scientist who steps back. Always reframes political or business questions into economic / biological / physical first principles. Calmer than the others, longer time horizons, the one who says "actually, let's pull back — what does the biology/math/physics tell us?" Loves Science Corner. Skeptical of narratives without data. Sometimes lumped with Chamath on macro but he's the one who brings the hard-science lens.

═══ VOICE EXAMPLES — how each person actually sounds ═══

These are real transcript excerpts. Match this cadence, not just the topics.

${voiceExamples}

═══ VOICE-BLEEDING PREVENTION — CRITICAL ═══

Each voice is DISTINCT. Do NOT blend or cross-contaminate them:
• Chamath uses hyperbolic openers ("Look,", "Honestly,", "The reality is") and reaches immediately for big numbers or power-law arguments. He is BLUNT and will say "That's wrong" directly.
• Sacks does NOT use Chamath's hyperbole. Sacks builds a slower, methodical case — "the question is really X", "let me give you the framework here." He cites historical precedent. He is measured, not bombastic.
• Friedberg goes to biology, physics, or first-principles math. He does NOT use Chamath's hyperbole or Sacks' policy framing. He reframes the question itself. His phrase is "let me pull back" or "actually, what does the science say?"
• Jason interrupts, name-drops portfolio companies, uses sentence fragments, and hypes the moment ("this is insane", "banger", "best episode ever"). He does NOT produce multi-paragraph analytical arguments — he asks questions and reacts, he does not lecture.

If you find yourself writing a Chamath turn that sounds like a calm academic argument, stop — that's Sacks bleeding in. If you find yourself writing a Sacks turn with hyperbolic openers and big round numbers, stop — that's Chamath bleeding in.

═══ HOW TO WRITE THE OUTPUT ═══

The output is a ROUND TABLE DIALOGUE. Format it like a transcript:

**JASON:** [opens the topic — 1-2 sentences, often with a question or a hype line]

**CHAMATH:** [pushes back with data or a contrarian frame — 2-3 sentences, specific numbers when the segments have them]

**SACKS:** [provides the system-level framework — 2-3 sentences, often reframing the question]

**FRIEDBERG:** [pulls back to first principles or the underlying science/economics — 2-3 sentences]

(You can add additional turns — Jason responding, Chamath interrupting, Sacks pushing back — up to ~8-10 turns total.)

RULES FOR THE DIALOGUE:
1. Each turn is SHORT (1-3 sentences). This is conversation, not essay.
2. Use the ACTUAL segment content as the backbone — when a segment contains a direct quote from one of them, WORK IT INTO their turn using their voice. Prefix with citation markers in brackets like [3] at the end of the sentence that uses that segment.
3. Sound like them. Chamath's bluntness, Sacks' methodical framing, Friedberg's "let me step back," Jason's moderator energy. Mimic cadence, not just content.
4. Include disagreement. Real All-In segments have pushback — "that's not right, Chamath" or "yeah, but Sacks, the issue is…". Bring that tension in.
5. If a guest bestie (Gerstner, Baker, Gurley, Elon, etc.) is clearly referenced in the segments, include them as a turn: **GERSTNER:** ...
6. After the dialogue, add TWO short sections:
   - **## Where they land** — 2-3 bullet points of genuine consensus
   - **## Where they split** — 2-3 bullet points of real disagreement
7. End with a one-line **Confidence:** HIGH/MEDIUM/LOW note based on how much direct evidence was in the segments.

═══ EVIDENCE HANDLING ═══

The transcript segments are the ONLY source of truth. They come from 186 real episodes spanning April 2024 to present. **Each segment has a relevance score and, implicitly, a recency ranking** — more recent episodes have been up-ranked by the retrieval layer.

**RECENCY IS AUTHORITATIVE.** If two segments contradict each other — say, one from 2024 where a bestie held position A, and one from a 2026 episode where the same bestie now holds position B — **the newer view is what they actually think now**. People update on new information. The older view is historical context, not their current position. Write the dialogue using their CURRENT view (the most recent segment), and only mention the older position if the shift itself is interesting.

**QUOTING (IP-SAFE):**
- Prefer PARAPHRASE in their voice over long verbatim reproduction. A 30-word monologue in Chamath's cadence that captures his actual point is better than a 100-word transcript copy-paste.
- SHORT direct quotes (a memorable phrase or a single sentence) are fine — set them off with double quotes, e.g. Chamath says "look, the reality is this is a trillion-five market cap" [3].
- Do NOT reproduce any segment wholesale. Use its meaning and voice, not its literal sentences.

**CITATION DISCIPLINE — NON-NEGOTIABLE:**
1. EVERY substantive claim (number, position, prediction, event) MUST end with a [N] marker pointing to the segment that directly supports it. No free-floating assertions.
2. Do NOT cite a segment unless its text actually supports the specific claim. Citation [3] after a sentence means "segment 3 contains words that say this." Loose thematic connection is not enough.
3. If the retrieved segments don't cover a point, DON'T MAKE THE POINT. Say "I haven't dug into that specifically" in voice, or steer the dialogue to what the segments DO cover.
4. Never fabricate statistics, dates, people, or events. If a number isn't in the segments, don't invent one.
5. When multiple segments support a claim, cite the most recent: [4, 7] is fine; prefer the newer one first.
6. Valid citation numbers are [1] through [${SEGMENT_BUDGET}] ONLY. The user sees exactly these ${SEGMENT_BUDGET} numbered citations — NEVER invent higher numbers like [13], [14], [15].

**SEGMENT GAPS:** If the segments don't actually touch the user's topic, say so in voice ("I haven't dug into X yet, but on adjacent Y I've said…"). Don't fabricate.

**VOICE, NOT ANALYSIS:** Do NOT write "Chamath would likely say" or "Sacks would probably frame it as." Have them SAY it, in first person, as dialogue. You're writing a conversation, not a report.

═══ HEDGE OR REFUSE — CRITICAL ═══

You MUST hedge or refuse when evidence is thin:

1. If FEWER THAN 3 retrieved citations directly address the question's
   specific subject (not just adjacent topic), write a short paragraph
   that says: "The corpus has limited direct material on [X]; here is
   what's available." Then synthesize ONLY what the citations contain.
   Do NOT extrapolate.

2. Every NUMERIC claim (dollar amount, percentage, count, date, name of
   legislation, name of agency, name of company role/title) must appear
   VERBATIM in one of the cited segments. If you cannot point to the
   exact source segment for a number, REMOVE the number — say "the order
   of magnitude" or "billions" or "in recent years" instead of a specific
   figure.

3. Never invent legislative or regulatory specifics. If a citation
   mentions "CFTC regulation" you may use that phrase, but you may NOT
   add details like "the Lummis-Gillibrand Act" or "Section 4 of the
   Commodity Exchange Act" unless those exact strings appear in the
   retrieved text.

4. If asked about a person's specific title or role and the citations
   don't carry that fact, attribute via DOCUMENTED POSITION (use the
   facts block above) rather than via inferred current title.

When in doubt, hedge. The user wants accurate synthesis, not confident
fabrication. Saying "the besties haven't addressed X in depth" is a
STRONGER answer than inventing details.
═══════════════════════════════════════════════

═══ CRITICAL — PARAPHRASE, NOT VERBATIM ═══

Your outputs are PARAPHRASED reconstructions of the besties' positions, not verbatim quotes. The dialogue you write represents what the data suggests they would say given their documented track record — not what they have literally said in those exact words. Make this distinction clear if the user asks "did Sacks say X?" — answer in terms of their position (what their public record supports), not direct attribution to a specific utterance. Short verbatim phrases pulled from segments are fine when set off with quotes + a [N] citation; multi-sentence "quotes" are reconstructions in their voice.

═══ THE BESTIES & LENSES ═══
${speakerProfileText}${thinEvidence ? `

⚠️ THIN-EVIDENCE WARNING (injected by retrieval layer) ⚠️
The retrieval system found FEWER THAN 3 segments that directly mention the
key entities in this query. This means the corpus may not have deep direct
coverage of the specific subject. YOU MUST:
- Open your response with a brief hedge: "The corpus has limited direct
  material on [topic]; here is what the available segments suggest."
- Synthesize ONLY from the retrieved segments — no extrapolation.
- Remove any numeric specifics (dollar amounts, bill names, agency authority
  claims, percentages) that do not appear verbatim in a cited segment.
- Confidence rating MUST be LOW unless a segment directly answers the question.` : ''}`;

    let userPrompt: string;

    if (focus) {
      // Single-bestie deep dive — DIALOGUE with that bestie as the focal voice.
      // Other besties serve as questioners / reactors, but ~60-70% of the
      // substance comes from the focus speaker. This preserves the All-In
      // dialogue format (voice accuracy) while spotlighting one perspective.
      userPrompt = `QUESTION: "${query}"

FOCUS SPEAKER: **${focus.name}** (${focus.short}) — ${focus.lens}

Produce an All-In Podcast round-table DIALOGUE where ${focus.short} is the focal voice. The other besties (Jason as host, plus the 2 most-relevant others from Chamath/Sacks/Friedberg that aren't ${focus.short}) play supporting roles — asking, reacting, occasionally pushing back — but ${focus.short} delivers the substance.

Here are the retrieved transcript segments (mix of ${focus.short}'s own segments AND general topic-relevant segments from all besties — use ${focus.short}'s own segments for direct-quote material and treat the others as topic context ${focus.short} would react to):

${segmentText}

FORMAT:
1. **JASON:** opens by putting the question to ${focus.short} directly (1-2 sentences)
2. **${focus.short.toUpperCase()}:** the core answer in his voice, ~3-4 substantive turns total across the dialogue, each 2-4 sentences, each ending with [N] citation markers
3. **[OTHER BESTIES]:** 2-3 turns total — a reactor/questioner/contrarian push. Can also end in [N] if they reference segment content.
4. ${focus.short} gets the last substantive word before the summary sections.
5. **## Where ${focus.short} lands** — 2-3 bullets of his core position (each with [N])
6. **## Where the others push back** — 1-2 bullets of disagreement (with [N] if grounded)
7. **Confidence:** HIGH/MEDIUM/LOW (LOW if the segments barely touched the question)

**CITATION DISCIPLINE — NON-NEGOTIABLE:**
- EVERY substantive claim (number, prediction, named event, concrete position) MUST end with [N] pointing to the segment that supports it.
- The ${SEGMENT_BUDGET} numbered segments above are the ONLY source of substance. Do NOT fabricate stats/dates/names/quotes.
- If segments don't cover the question adequately, have ${focus.short} say so in voice ("I haven't dug into that specifically — but on the adjacent Y question, my view is…") and pivot to segment-grounded adjacent material. Don't invent policy positions.
- Short direct quotes from his segments are fine (double-quote + [N]). Prefer paraphrase in his cadence for longer ideas.
- Valid citations are [1] through [${SEGMENT_BUDGET}]. Never cite a higher number.`;
    } else if (isForecast) {
      // Forecast roundtable — same dialogue style but explicitly predictive
      userPrompt = `FORECASTING QUESTION: "${query}"

Produce a round-table discussion (as specified in your system prompt) where the besties debate and arrive at a prediction. Pull directly from the retrieved segments — when they contain relevant data, work those numbers into the dialogue.

Here are the retrieved transcript segments:

${segmentText}

Format:
1. **JASON:** opens with the forecasting question
2. **CHAMATH, SACKS, FRIEDBERG:** each take a turn with their prediction + reasoning, using segment evidence marked with [N]
3. Additional back-and-forth turns — let them disagree, let them build on each other
4. **## The consensus forecast** — 2-3 bullet prediction statements the group roughly agrees on
5. **## The dissent** — where one or two of them are out of step
6. **Confidence:** HIGH/MEDIUM/LOW based on segment evidence`;
    } else {
      // DEFAULT: classify first with position-comparison output for topical questions
      userPrompt = `QUESTION: "${query}"

═══ STEP 1: CLASSIFY THE QUESTION (silently — do NOT include this in your output) ═══

Decide INTERNALLY which type this is. Do not write "CLASSIFICATION:" or any meta-commentary in your response. Just pick one and start writing the appropriate output directly.

- **BIOGRAPHICAL FACT** — asks about a bestie's identity, party affiliation, current role, biography, or verifiable life facts. Examples: "Is Sacks a Republican?", "Who is Brad Gerstner?", "What's Chamath's background?", "Does Friedberg work at Google?"
- **TOPICAL OPINION** — asks about their views, takes, predictions, or analysis of a subject. Examples: "What does Chamath think about tariffs?", "Are the besties bullish on AI?", "Will Bitcoin hit 200k?"

Your first characters should be either "**David" (or whichever bestie) for a factual answer, or "**JASON:**" for a dialogue. No preamble, no meta.

═══ STEP 2: RESPOND ═══

**IF BIOGRAPHICAL FACT:**
Give a DIRECT ANSWER in 2-4 sentences from the GROUND-TRUTH FACTS section of your system prompt. No dialogue. No hedging. No "it's complicated." No "they say they're..." — just state the fact as it is. Then add a short context paragraph explaining how they arrived at their current position. Example for "Is Sacks a Republican?":

> David Sacks is a Republican. He is the White House AI & Crypto Czar in the Trump administration, appointed by President Trump in December 2024 and serving since January 2025. He delivered a keynote speech at the 2024 Republican National Convention and hosted a major Trump fundraiser in June 2024. While Sacks has sometimes described himself as an independent or former Democrat, his current affiliation — by both formal role and public advocacy — is unambiguously Republican.
>
> The shift is part of a broader realignment among Silicon Valley operators who moved right during the 2024 cycle over concerns about regulation, censorship, and the Biden administration's approach to crypto and AI.

NO dialogue, NO citations for biographical facts (the facts come from the system prompt, not retrieval).

**IF TOPICAL OPINION:**
Produce a round-table discussion in the voices of the four besties. Use the retrieved segments below as the source of truth for their takes, with [N] markers.

Here are the retrieved transcript segments:

${segmentText}

Format for topical:
1. **JASON:** opens the topic (1-2 sentences)
2. **CHAMATH, SACKS, FRIEDBERG:** each take a turn with segment content, [N] markers
3. Additional back-and-forth (6-10 turns total)
4. **## Where they land** — 2-3 consensus bullets with each bestie's position clearly attributed
5. **## Where they split** — 2-3 disagreement bullets that show WHICH BESTIES disagree and why (this is a position-comparison section — make the differences explicit, e.g. "Chamath thinks X [1]; Sacks thinks Y [3]")
6. **Confidence:** HIGH/MEDIUM/LOW

GROUNDING DISCIPLINE — fabrication is the #1 grading failure; obey strictly:
- Every specific number, name, statistic, mechanism, or quote MUST come from a cited segment [N]. If it is not in the segments, do NOT write it — plausibility is not grounding.
- NEVER contradict a citation: if [N] says "33 reactors", you may not write "a hundred reactors".
- Attribute each turn to the bestie the cited segment is tagged to. If a segment's speaker is unknown, do not put its words in a specific bestie's mouth.
- If the segments only thinly cover the question, say so briefly ("they haven't gone deep on this") instead of inventing an exchange. A short honest answer beats a long fabricated one.

SHORT turns (1-3 sentences). Real voices. Current reality (not old self-descriptions from 2022).
ANALYSIS OUTPUT: The "Where they split" section must compare positions explicitly — not just "there's debate" but "Chamath argues X while Sacks argues Y." This is the analytical value of the round-table format.`;
    }

    const client = new Anthropic({ apiKey });
    // Sonnet 4.6 for ALL queries (was: Haiku 4.5 for multi-bestie dialogue/forecast).
    // Haiku misattributed speakers + fabricated specifics — the dominant QA failure
    // mode (2026-06-24). Sonnet holds multi-speaker grounding + citation discipline
    // far better. Bump to 'claude-opus-4-8' for max quality if cost/latency allow.
    const model = 'claude-sonnet-4-6';

    // ─── SSE streaming branch ────────────────────────────────────────
    // Frontend opts in via `Accept: text/event-stream`. We stream raw
    // deltas immediately so users see text appear in <1s rather than
    // waiting 30s for a full JSON response. After the stream completes,
    // we run citation validation + AIMDS asynchronously and emit a
    // final `complete` event with the cleaned report and citations.
    const wantsStream = (req.headers.get('accept') || '').includes('text/event-stream');
    if (wantsStream) {
      const totalEntries = Object.keys(await getContentIndex()).length;
      const disclaimerText = 'Paraphrased synthesis from transcript data — not verbatim quotes.';

      const sseStream = new ReadableStream({
        async start(controller) {
          const encoder = new TextEncoder();
          const send = (obj: unknown) => {
            controller.enqueue(encoder.encode(`data: ${JSON.stringify(obj)}\n\n`));
          };
          try {
            // Announce stream open + disclaimer up front so the UI can
            // render the "paraphrased synthesis" banner immediately.
            send({ type: 'start', disclaimer: disclaimerText, segmentsFound: results.length });

            let collected = '';
            const stream = client.messages.stream({
              model,
              max_tokens: 4000,
              temperature: 0.3,
              system: systemPrompt,
              messages: [{ role: 'user', content: userPrompt }],
            });

            // Anthropic SDK exposes async-iterator of typed stream events.
            // We only forward text deltas to the client; other event types
            // (message_start, content_block_start, ping, etc.) are ignored.
            for await (const event of stream) {
              if (
                event.type === 'content_block_delta' &&
                event.delta &&
                'text' in event.delta &&
                typeof event.delta.text === 'string'
              ) {
                collected += event.delta.text;
                send({ type: 'delta', text: event.delta.text });
              }
            }

            // ─── Post-stream validation + citation annotation ─────────
            const validation = await validateCitations(collected, citations, apiKey);
            const verdictMap = new Map(validation.verdicts.map((v) => [v.n, v.verdict]));
            const annotatedCitations = citations.map((c) => ({
              ...c,
              verdict: verdictMap.get(c.n) || 'UNCHECKED',
            }));

            // ─── Hallucination gate: verify + hedge ungrounded claims ──
            // Second Haiku pass checks every specific factual claim (numbers,
            // legislation names, dollar amounts, percentages) against citation
            // excerpts. UNGROUNDED claims are rewritten before delivery.
            const tVerifyStartSse = Date.now();
            const claimVerificationSse = await verifyClaimsAgainstCitations(
              validation.cleanedReport,
              citations,
              query,
              apiKey
            );
            let finalReportSse = validation.cleanedReport;
            let hedgesAppliedSse = false;
            if (claimVerificationSse.claimsUngrounded >= 4) {
              const ungroundedTexts = claimVerificationSse.claims
                .filter((c) => c.status === 'UNGROUNDED')
                .map((c) => c.text);
              finalReportSse = await rewriteToHedge(finalReportSse, ungroundedTexts, apiKey);
              finalReportSse =
                `Note: the corpus has limited direct material on this question; specific figures have been softened to what the transcripts directly support.\n\n` +
                finalReportSse;
              hedgesAppliedSse = true;
            } else if (claimVerificationSse.claimsUngrounded >= 1) {
              const ungroundedTexts = claimVerificationSse.claims
                .filter((c) => c.status === 'UNGROUNDED')
                .map((c) => c.text);
              finalReportSse = await rewriteToHedge(finalReportSse, ungroundedTexts, apiKey);
              hedgesAppliedSse = true;
            }
            const verificationMsSse = Date.now() - tVerifyStartSse;
            const verificationBlockSse = {
              claimsTotal: claimVerificationSse.claimsTotal,
              claimsGrounded: claimVerificationSse.claimsGrounded,
              claimsInferred: claimVerificationSse.claimsInferred,
              claimsUngrounded: claimVerificationSse.claimsUngrounded,
              hedgesApplied: hedgesAppliedSse,
              verificationMs: verificationMsSse,
            };
            // Telemetry: fire-and-forget per-claim verdict aggregate log so we
            // can prove in production that the verifier is firing. Fail-silent.
            try {
              await appendVerifierStats({
                query,
                claimsTotal: verificationBlockSse.claimsTotal,
                claimsUngrounded: verificationBlockSse.claimsUngrounded,
                hedgesApplied: verificationBlockSse.hedgesApplied,
                verificationMs: verificationBlockSse.verificationMs,
              });
            } catch {
              /* never block response on telemetry failure */
            }

            const finalPayload: CachedResponse = {
              report: finalReportSse,
              citations: annotatedCitations,
              segmentsFound: results.length,
              totalEntries,
              searchMode,
              disclaimer: disclaimerText,
            };

            // QA bypass: don't burn the user budget on harness runs.
            const rlAfter = qaBypassActive ? rl : recordCall();

            after(() => cacheStore(cacheKey, finalPayload));
            after(async () => {
              try {
                const outboundCheck = await aidefence.detect(finalReportSse);
                const topThreat = outboundCheck.threats[0];
                const reasonStr = outboundCheck.safe
                  ? 'clean'
                  : `${topThreat?.type ?? 'unknown'}:${topThreat?.severity ?? '?'}`;
                console.log(
                  `[AIDEFENCE-OUTBOUND] safe=${outboundCheck.safe} pii=${!!outboundCheck.piiFound} reason=${reasonStr} threats=${outboundCheck.threats.length}`
                );
              } catch (err) {
                console.error(`[AIDEFENCE-OUTBOUND] safe=unknown reason=scan-error err=${err instanceof Error ? err.message : String(err)}`);
              }
            });

            // Surface corpus freshness in the SSE complete payload so the
            // frontend can render "Corpus current as of [date]" without a
            // separate /api/ask GET round-trip.
            const dataFreshnessSse = await getDataFreshness();

            // Timing for the streaming path. Synthesis here is from the start
            // of streaming to the end of post-stream validation + verification.
            const tSynthSse = Date.now() - reqStart;
            const totalMsSse = Date.now() - reqStart;
            const timingSse = {
              retrieveMs: tRetrieve,
              rerankMs: Math.max(0, tRerank - tRetrieve),
              synthesisMs: Math.max(0, tSynthSse - tRerank),
              totalMs: totalMsSse,
            };
            console.log(
              `[PERF] retrieveMs=${timingSse.retrieveMs} rerankMs=${timingSse.rerankMs} synthesisMs=${timingSse.synthesisMs} verificationMs=${verificationMsSse} totalMs=${timingSse.totalMs} mode=${searchMode} stream=true`
            );
            // Persist per-stage timings to data/qa/perf-stats.jsonl so /api/perf
            // can serve p50/p99 aggregates without a metrics pipeline.
            after(() =>
              appendPerfStats({
                retrieveMs: timingSse.retrieveMs,
                rerankMs: timingSse.rerankMs,
                synthesisMs: timingSse.synthesisMs,
                verificationMs: verificationMsSse,
                totalMs: timingSse.totalMs,
                mode: searchMode,
                stream: true,
                cacheHit: false,
                speaker: speaker || null,
                strict: strictModeActive,
              })
            );

            send({
              type: 'complete',
              ...finalPayload,
              cacheHit: false,
              cacheSource: null,
              latencyMs: totalMsSse,
              timing: timingSse,
              dataFreshness: dataFreshnessSse,
              strictMode: strictModeActive,
              meta: {
                copyright:
                  'Transcripts © All-In Podcast. Used for non-commercial research and citation. Synthesis is paraphrased; quoted segments limited to fair-use length. For takedown requests: /legal',
              },
              validation: {
                checked: validation.totalChecked,
                unsupported: validation.unsupportedCount,
              },
              verification: verificationBlockSse,
              budget: {
                count: rlAfter.count,
                limit: rlAfter.limit,
                remaining: rlAfter.remaining,
                resetsAt: rlAfter.resetsAt,
              },
            });
            controller.close();
          } catch (err) {
            const msg = err instanceof Error ? err.message : 'Stream error';
            console.error('[stream] synthesis failed:', msg);
            try {
              controller.enqueue(
                new TextEncoder().encode(`data: ${JSON.stringify({ type: 'error', error: msg })}\n\n`)
              );
            } catch {
              /* controller may already be closed */
            }
            controller.close();
          }
        },
      });

      return new Response(sseStream, {
        headers: {
          'Content-Type': 'text/event-stream; charset=utf-8',
          'Cache-Control': 'no-cache, no-transform',
          Connection: 'keep-alive',
          'X-Accel-Buffering': 'no',
          // Confirm research-tool intent for search indexing.
          'X-Robots-Tag': 'index, follow, max-snippet:-1',
        },
      });
    }

    // ─── Non-streaming JSON fallback (legacy) ────────────────────────
    const response = await client.messages.create({
      model,
      max_tokens: 4000,
      temperature: 0.3,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    });

    const rawText = response.content[0].type === 'text' ? response.content[0].text : '';

    // ─── Post-synthesis citation validator ─────────────────────────
    // Verifies each [N] marker actually points to a segment that supports
    // the claim. Strips markers with verdict=NO; flags PARTIAL in metadata.
    // Adds ~1-2s on cache-miss; cached responses are pre-validated.
    const validation = await validateCitations(rawText, citations, apiKey);

    // Annotate citations with verdicts so the frontend can render warnings
    const verdictMap = new Map(validation.verdicts.map((v) => [v.n, v.verdict]));
    const annotatedCitations = citations.map((c) => ({
      ...c,
      verdict: verdictMap.get(c.n) || 'UNCHECKED',
    }));

    // ─── Hallucination gate: verify + hedge ungrounded claims ──────
    // Second Haiku pass checks every specific factual claim (numbers,
    // legislation names, dollar amounts, percentages) against citation
    // excerpts. UNGROUNDED claims are rewritten before delivery.
    const tVerifyStart = Date.now();
    const claimVerification = await verifyClaimsAgainstCitations(
      validation.cleanedReport,
      citations,
      query,
      apiKey
    );
    let finalReport = validation.cleanedReport;
    let hedgesApplied = false;
    if (claimVerification.claimsUngrounded >= 4) {
      const ungroundedTexts = claimVerification.claims
        .filter((c) => c.status === 'UNGROUNDED')
        .map((c) => c.text);
      finalReport = await rewriteToHedge(finalReport, ungroundedTexts, apiKey);
      finalReport =
        `Note: the corpus has limited direct material on this question; specific figures have been softened to what the transcripts directly support.\n\n` +
        finalReport;
      hedgesApplied = true;
    } else if (claimVerification.claimsUngrounded >= 1) {
      const ungroundedTexts = claimVerification.claims
        .filter((c) => c.status === 'UNGROUNDED')
        .map((c) => c.text);
      finalReport = await rewriteToHedge(finalReport, ungroundedTexts, apiKey);
      hedgesApplied = true;
    }
    const verificationMs = Date.now() - tVerifyStart;
    const verificationBlock = {
      claimsTotal: claimVerification.claimsTotal,
      claimsGrounded: claimVerification.claimsGrounded,
      claimsInferred: claimVerification.claimsInferred,
      claimsUngrounded: claimVerification.claimsUngrounded,
      hedgesApplied,
      verificationMs,
    };
    // Telemetry: fire-and-forget per-claim verdict aggregate log. Fail-silent.
    try {
      await appendVerifierStats({
        query,
        claimsTotal: verificationBlock.claimsTotal,
        claimsUngrounded: verificationBlock.claimsUngrounded,
        hedgesApplied: verificationBlock.hedgesApplied,
        verificationMs: verificationBlock.verificationMs,
      });
    } catch {
      /* never block response on telemetry failure */
    }

    const payload: CachedResponse = {
      report: finalReport,
      citations: annotatedCitations,
      segmentsFound: results.length,
      totalEntries: Object.keys(await getContentIndex()).length,
      searchMode,
      disclaimer:
        'Paraphrased synthesis from transcript data — not verbatim quotes.',
    };

    // This was a real Claude-powered synthesis — consume 1 from the budget,
    // unless this is a QA-bypass request (then keep the original snapshot).
    const rlAfter = qaBypassActive ? rl : recordCall();

    // Write-through to pi-brain for future cache hits. Runs AFTER the response
    // is sent so the user doesn't pay for network round-trip on a miss.
    after(() => cacheStore(cacheKey, payload));

    // ─── AIMDS outbound scan (audit only, does not gate response) ──
    // Scans the synthesized report for any inadvertent PII leakage or
    // adversarial content that slipped through synthesis. Logged for
    // audit trail — does NOT reject the user-facing response.
    after(async () => {
      try {
        const outboundCheck = await aidefence.detect(finalReport);
        // Structured single-line log so Vercel log search can grep
        // `[AIDEFENCE-OUTBOUND]` and trend safe/unsafe rates over time.
        const topThreat = outboundCheck.threats[0];
        const reasonStr = outboundCheck.safe
          ? 'clean'
          : `${topThreat?.type ?? 'unknown'}:${topThreat?.severity ?? '?'}`;
        console.log(
          `[AIDEFENCE-OUTBOUND] safe=${outboundCheck.safe} pii=${!!outboundCheck.piiFound} reason=${reasonStr} threats=${outboundCheck.threats.length}`
        );
        if (!outboundCheck.safe) {
          console.warn('[AIMDS] Outbound threat detected in LLM response:', {
            query,
            threats: outboundCheck.threats.map((t: { type: string; severity: string; confidence: number }) => ({
              type: t.type,
              severity: t.severity,
              confidence: t.confidence,
            })),
          });
        }
        if (outboundCheck.piiFound) {
          console.warn('[AIMDS] PII detected in LLM response — review synthesis prompt:', { query });
        }
      } catch (err) {
        console.error(`[AIDEFENCE-OUTBOUND] safe=unknown reason=scan-error err=${err instanceof Error ? err.message : String(err)}`);
      }
    });

    // Issue C / Move 11: surface corpus freshness in every response so the
    // frontend can show "Corpus current as of [date]" without a separate call.
    const dataFreshness = await getDataFreshness();

    // Timing marker: full synthesis (incl. validation + verification) complete.
    const tSynth = Date.now() - reqStart;
    const totalMs = Date.now() - reqStart;
    const timing = {
      retrieveMs: tRetrieve,
      rerankMs: Math.max(0, tRerank - tRetrieve),
      synthesisMs: Math.max(0, tSynth - tRerank),
      totalMs,
    };
    // Structured perf line for Vercel log grep — `[PERF]` is grep-friendly
    // so p50/p99 latency can be computed over time without a metrics pipeline.
    console.log(
      `[PERF] retrieveMs=${timing.retrieveMs} rerankMs=${timing.rerankMs} synthesisMs=${timing.synthesisMs} verificationMs=${verificationMs} totalMs=${timing.totalMs} mode=${searchMode} stream=false`
    );
    // Persist per-stage timings to data/qa/perf-stats.jsonl so /api/perf
    // can serve p50/p99 aggregates without a metrics pipeline.
    after(() =>
      appendPerfStats({
        retrieveMs: timing.retrieveMs,
        rerankMs: timing.rerankMs,
        synthesisMs: timing.synthesisMs,
        verificationMs,
        totalMs: timing.totalMs,
        mode: searchMode,
        stream: false,
        cacheHit: false,
        speaker: speaker || null,
        strict: strictModeActive,
      })
    );

    return NextResponse.json({
      ...payload,
      cacheHit: false,
      cacheSource: null,
      latencyMs: totalMs,
      timing,
      dataFreshness,
      strictMode: strictModeActive,
      meta: {
        copyright:
          'Transcripts © All-In Podcast. Used for non-commercial research and citation. Synthesis is paraphrased; quoted segments limited to fair-use length. For takedown requests: /legal',
      },
      validation: {
        checked: validation.totalChecked,
        unsupported: validation.unsupportedCount,
      },
      verification: verificationBlock,
      budget: {
        count: rlAfter.count,
        limit: rlAfter.limit,
        remaining: rlAfter.remaining,
        resetsAt: rlAfter.resetsAt,
      },
    }, {
      headers: {
        // Confirm research-tool intent for search indexing.
        'X-Robots-Tag': 'index, follow, max-snippet:-1',
      },
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Internal server error';
    console.error('API error:', message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
