#!/bin/bash
# Weekly update for All-In Expert KB
# Runs every Saturday: refreshes RSS, downloads new episode captions,
# rebuilds the knowledge base, and redeploys to Vercel.
#
# Install as LaunchAgent: com.isovision.all-in-expert.weekly

set -o pipefail
ROOT="/Users/stuartkerr/Code/All In Expert"
LOG_DIR="$HOME/.claude/logs"
LOG_FILE="$LOG_DIR/all-in-expert-weekly.log"
mkdir -p "$LOG_DIR"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S %Z')] $*" | tee -a "$LOG_FILE"
}

log "═══ Weekly All-In Expert update starting ═══"
cd "$ROOT" || { log "ERROR: Cannot cd to $ROOT"; exit 1; }

# 1. Refresh RSS feed (get latest episodes)
log "Refreshing RSS feed..."
curl -sL "https://rss.libsyn.com/shows/254861/destinations/1928300.xml" \
    -o "data/episodes/rss_feed.xml" || {
    log "ERROR: RSS download failed"
    exit 1
}
log "RSS feed refreshed ($(wc -c < data/episodes/rss_feed.xml) bytes)"

# 2. Re-parse RSS into metadata JSON
log "Parsing RSS metadata..."
python3 -c "
import xml.etree.ElementTree as ET
import json
from datetime import datetime

tree = ET.parse('data/episodes/rss_feed.xml')
root = tree.getroot()
ns = {'itunes': 'http://www.itunes.com/dtds/podcast-1.0.dtd'}

episodes = []
for item in root.findall('.//item'):
    title = item.find('title').text if item.find('title') is not None else ''
    pub_date = item.find('pubDate').text if item.find('pubDate') is not None else ''
    enclosure = item.find('enclosure')
    audio_url = enclosure.get('url', '') if enclosure is not None else ''
    duration = item.find('itunes:duration', ns)
    dur_text = duration.text if duration is not None else ''
    try:
        dt = datetime.strptime(pub_date.strip(), '%a, %d %b %Y %H:%M:%S %z')
        date_str = dt.strftime('%Y-%m-%d')
        year = dt.year
        month = dt.month
    except:
        date_str = pub_date
        year = 0
        month = 0
    if year >= 2024 and (year > 2024 or month >= 4):
        episodes.append({
            'title': title, 'date': date_str,
            'audio_url': audio_url, 'duration': dur_text
        })
with open('data/episodes/episodes_metadata.json', 'w') as f:
    json.dump(episodes, f, indent=2)
print(f'{len(episodes)} episodes')
" >> "$LOG_FILE" 2>&1 || { log "ERROR: RSS parse failed"; exit 1; }

# 3. Refresh YouTube video ID list
log "Refreshing YouTube video catalog..."
yt-dlp --flat-playlist --print "%(id)s\t%(title)s" \
    "https://www.youtube.com/@allin/videos" 2>/dev/null \
    > data/episodes/all_video_ids_raw.tsv || {
    log "WARN: yt-dlp flat-playlist failed; keeping existing TSV"
}
if [ -s data/episodes/all_video_ids_raw.tsv ]; then
    # Fix literal \t issue
    python3 -c "
with open('data/episodes/all_video_ids_raw.tsv','r') as f:
    c = f.read()
with open('data/episodes/all_video_ids.tsv','w') as f:
    f.write(c.replace('\\\\t', '\t'))
"
    rm -f data/episodes/all_video_ids_raw.tsv
    log "YouTube catalog: $(wc -l < data/episodes/all_video_ids.tsv) videos"
fi

# 4. Download any new episode captions
log "Downloading new captions..."
bash scripts/bulk-download.sh 500 >> "$LOG_FILE" 2>&1 || {
    log "WARN: Some caption downloads failed (continuing)"
}

# 5. Reprocess transcripts (includes new episodes)
log "Reprocessing transcripts..."
node scripts/process-captions.mjs >> "$LOG_FILE" 2>&1 || {
    log "ERROR: Transcript processing failed"
    exit 1
}

# 6. Rebuild knowledge base with real embeddings
log "Rebuilding knowledge base..."
rm -f data/kb/all-in-expert.rvf 2>/dev/null
node scripts/build-knowledge-base.mjs >> "$LOG_FILE" 2>&1 || {
    log "ERROR: KB rebuild failed"
    exit 1
}

# 7. Rebuild chapter index (topics from show notes)
log "Rebuilding chapter index..."
node scripts/extract-chapters.mjs >> "$LOG_FILE" 2>&1 || {
    log "ERROR: Chapter extraction failed"
    exit 1
}

# 8. Rebuild episode-dates for recency weighting
log "Rebuilding episode dates map..."
node scripts/build-episode-dates.mjs >> "$LOG_FILE" 2>&1 || {
    log "WARN: Episode dates build failed (continuing)"
}

# 9. Commit data changes
log "Committing data changes..."
cd "$ROOT"
git add web/public/data/ data/kb/_manifest.json 2>/dev/null
if git diff --cached --quiet; then
    log "No data changes to commit"
else
    git commit -m "Weekly KB refresh: $(date '+%Y-%m-%d')

Auto-generated by weekly-update.sh
- Refreshed RSS, captions, transcripts
- Rebuilt RVF knowledge base
- Re-indexed chapters from show notes

🤖 Automated weekly update" >> "$LOG_FILE" 2>&1
    git push origin main >> "$LOG_FILE" 2>&1 || log "WARN: Git push failed"
fi

# 10. Deploy to Vercel
log "Deploying to Vercel..."
cd "$ROOT/web"
vercel --prod --yes --scope stuart-kerrs-projects >> "$LOG_FILE" 2>&1 || {
    log "ERROR: Vercel deploy failed"
    exit 1
}

# 11. Re-alias
vercel alias set "$(vercel inspect --scope stuart-kerrs-projects 2>/dev/null | grep -o 'https://web-[a-z0-9-]*\.vercel\.app' | head -1)" asktheallinexperts.vercel.app >> "$LOG_FILE" 2>&1 || {
    log "WARN: Re-alias failed"
}

log "═══ Weekly update complete ═══"
echo "" >> "$LOG_FILE"
